port: 8080
mysql:
  host: "121.196.60.92"
  port: 3306
  name: "pick_v2"
  user: "root"
  password: "bnskdfglnbbgf"
jwt:
  key: 'ghlasdfkgbnkadfjbgnksdfjsdfgnbjk'
redis:
  host: 192.168.0.1
  port: 6379
  expire: 1